educ_ols = lm(educ ~ motheduc + fatheduc + abil + I(abil^2), data = htv)
summary(educ_ols)
wald.test(Sigma = vcov(educ_ols),b = coef(educ_ols), Terms = 5)
linearHypothesis(educ_ols, "motheduc = fatheduc")
educ_ols2 = lm(educ ~ motheduc + fatheduc + abil + I(abil^2)+ tuit17 + tuit18, data = htv)
summary(educ_ols2)
wald.test(Sigma = vcov(educ_ols2),b = coef(educ_ols2), Terms = 6:7)
educ_ols3 = lm(educ ~ motheduc + fatheduc + abil + I(abil^2)+ I(0.5 * tuit17 + 0.5 * tuit18), data = htv)
summary(educ_ols3)
cor(htv)
hist(htv[n("educ")])